max_width = 100
imports_granularity = "Crate"
use_small_heuristics = "Max"

comment_width = 100
wrap_comments = true
normalize_comments = true
normalize_doc_attributes = true
format_code_in_doc_comments = true
