[package]
name = "paper-rs"
version = "0.0.1"
description = "The WASM engine for Paperarium"
authors = ["Evan Kirkiles"]
repository = "https://github.com/evankirkiles/papercraft-client"
edition = "2021"

[features]
default = ["console_error_panic_hook"]

[lib]
crate-type = ["cdylib", "rlib"] # Support both WASM and Native compilation

# ------------------ Shared Dependencies ------------------

[dependencies]
anyhow = "1.0"
cfg-if = "1"
log = "0.4"
pollster = "0.4"
tobj = { version = "4.0", default-features = false, features = ["async"] }
winit = { version = "0.29", features = ["rwh_05"] }
wgpu = { version = "23.0", features = ["wgsl", "webgl"] }
bytemuck = { version = "1.19", features = ["derive"] }
cgmath = "0.18"

[dependencies.image]
version = "0.25"
default-features = false
features = ["png", "jpeg"]

[build-dependencies]
anyhow = "1.0"
fs_extra = "1.2"
glob = "0.3"

# ------------------ Native Dependencies ------------------

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
env_logger = "0.11"

# ------------------- WASM Dependencies -------------------

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = { version = "0.1.7", optional = true }
console_log = "1.0.0"
reqwest = "0.12"
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
web-sys = { version = "0.3", features = [
  "Window",
  "Document",
  "HtmlCanvasElement",
  "Location",
  "console",
] }

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
wasm-bindgen-test = "0.3.45"

# [profile.release]
# opt-level = "s"
