[package]
name = "crate"
version = "0.0.1"
description = "The WASM engine for Paperarium"
authors = ["Evan Kirkiles"]
edition = "2021"

[features]
default = ["console_error_panic_hook"]

[lib]
crate-type = ["cdylib"]

[dependencies]
console_error_panic_hook = { version = "0.1.7", optional = true }
console_log = "1.0.0"
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
wgpu = { version = "23.0", features = ["wgsl", "webgl"] }
winit = { version = "0.29", features = ["rwh_05"] }

[dependencies.web-sys]
version = "0.3"
features = ["Window", "Document", "HtmlCanvasElement", "console"]

[dev-dependencies]
wasm-bindgen-test = "0.3.45"

[profile.release]
opt-level = "s"
