[package]
name = "crate"
version = "0.0.1"
description = "The WASM engine for Paperarium"
authors = ["Evan Kirkiles"]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
js-sys = { version = "0.3.72" }
wasm-bindgen = "0.2.95"
serde = { version = "1.0.213", features = ["derive"] }
serde-wasm-bindgen = "0.6.5"


# The `console_error_panic_hook` crate provides better debugging of panics by
# # logging them with `console.error`. This is great for development, but requires
# # all the `std::fmt` and `std::panicking` infrastructure, so isn't great for
# # code size when deploying.
console_error_panic_hook = { version = "0.1.7", optional = true }

[dependencies.web-sys]
version = "0.3.72"
features = [
  "Document",
  "Element",
  "HtmlCanvasElement",
  "WebGlBuffer",
  "WebGlVertexArrayObject",
  "WebGl2RenderingContext",
  "WebGlProgram",
  "WebGlShader",
  "Window",
]

[dev-dependencies]
wasm-bindgen-test = "0.3.45"

[profile.release]
# Tell `rustc` to optimize for small code size
opt-level = "s"

[features]
default = ["console_error_panic_hook"]
